### ISSUE TITLE
Add this into a list view builder?

### ISSUE THREAD

**Issue by developerflutter** [yuto-yuto/flutter_samples#1]
I have one scenario, to include these dynamic number of textfields into a Listview builder. How can I achieve this? I can add but how can I define controllers for each?

**Comment by yuto-yuto** [comment]
What do you mean "define" exactly? If you can add it you can set whatever you want. I think it's "define a controller".

Did you read one of these? Read the corresponding article if you haven't read it. 

* [Code With Riverpod](https://github.com/yuto-yuto/flutter_samples/blob/main/lib/riverpod/dynamic_textfield_with_riverpod.dart)
-> Article: https://www.technicalfeeder.com/2021/09/flutter-add-textfield-dynamically/
* [Code Without Riverpod](https://github.com/yuto-yuto/flutter_samples/blob/main/lib/dynamic_text_field.dart)
-> Article: https://www.technicalfeeder.com/2021/10/flutter-dynamic-textfield-creation-with-riverpod/

**Comment by developerflutter** [comment]
Suppose I have three controllers that's defined dynamically, say Name, Mobile, and Address. The solution working fine. Now If I want to add multiple number of groups, how can I set the controllers?

**Comment by yuto-yuto** [comment]
Do you want to handle those 3 TextFields together?
There are 2 ways to do it.

1. Define 3 different variables. Use them with the same index to access a group.
```dart
List<TextEditingController> _nameControllers = [];
List<TextEditingController> _mobileControllers = [];
List<TextEditingController> _addressControllers = [];
...
// show the text for the group
print(_nameControllers[index].text);
print(_mobileControllers[index].text);
print(_addressControllers[index].text);
```

2. Create a class that has those 3 controllers and define a List<GroupControllers>. 
```dart
class _GroupControllers {
  TextEditingController name = TextEditingController();
  TextEditingController tel = TextEditingController();
  TextEditingController address = TextEditingController();
  void dispose() {
    name.dispose();
    tel.dispose();
    address.dispose();
  }
}
```

I added the examples here. 
https://github.com/yuto-yuto/flutter_samples/blob/main/lib/dynamic_text_field.dart

If you want to watch a video for the example, I placed it at the bottom of this article
[Flutter Add TextField widget dynamically](https://www.technicalfeeder.com/2021/09/flutter-add-textfield-dynamically/?preview_id=847&preview_nonce=0507687307&preview=true&_thumbnail_id=852)

**Comment by developerflutter** [comment]
If we can say there is only three or four controllers then this is fine. We can predefine the controllers first. In my case I cannot say that how many controllers will be listed. It is completely based end point data.It may be five, six or ten. 

How can we manage this?

**Comment by yuto-yuto** [comment]
See [this](https://www.technicalfeeder.com/2021/09/flutter-add-textfield-dynamically/#toc5). It reads data from a function which returns `Future<List<String>>`. This example creates fixed data in the function but what you need to do is basically the same. You probably have a function to fetch data from a database or somewhere else and it definitely returns Future type.

Use FutureBuilder instead of normal ListView. Once you fetch the data from a database, you can definitely get the length of the data. It means that you can use for-loop to create the controllers dynamically.

**Comment by developerflutter** [comment]
<img width="376" alt="Screen Shot 2021-11-25 at 4 23 34 PM" src="https://user-images.githubusercontent.com/54549071/143449374-2a310012-3f4e-44ff-a19c-4a26137b2c6f.png">

Please check the screenshot, I am expecting the result as mentioned

**Comment by yuto-yuto** [comment]
I've already given you all necessary info. I can help you but I don't impelment the app above. It's your job.
